[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

remappings = [
    "@metamask/delegation-framework/=lib/delegation-framework/src/",
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }
